from __future__ import annotations

import argparse
import importlib.util
import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import unittest
from unittest import mock
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class RepositoryDocsTests(unittest.TestCase):
    def _copy_repository(self, destination: Path) -> None:
        for name in (".gitattributes", "README.md", "THIRD_PARTY_NOTICES.md", "pyproject.toml"):
            shutil.copy2(ROOT / name, destination / name)
        for name in ("docs", "skills", "src", "third_party", "tools"):
            shutil.copytree(ROOT / name, destination / name)
        (destination / "tests/fixtures").mkdir(parents=True)
        shutil.copytree(ROOT / "tests/fixtures", destination / "tests/fixtures", dirs_exist_ok=True)

    def _run_checker(self, root: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(root / "tools/check_repository_docs.py")],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
        )

    def _empty_skill_description(self, root: Path) -> None:
        path = root / "skills/ima-note-cli/SKILL.md"
        lines = path.read_text(encoding="utf-8").splitlines()
        lines = ["description:" if line.startswith("description:") else line for line in lines]
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def test_repository_checker_passes(self) -> None:
        result = subprocess.run(
            [sys.executable, str(ROOT / "tools/check_repository_docs.py")],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_cli_reference_check_passes(self) -> None:
        result = subprocess.run(
            [sys.executable, str(ROOT / "tools/render_cli_reference.py"), "--check"],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_manifest_has_one_repository_only_skill(self) -> None:
        manifest = json.loads((ROOT / "skills/manifest.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["canonical_skill"], "ima-note-cli")
        self.assertEqual(len(manifest["skills"]), 1)
        self.assertEqual(manifest["skills"][0]["distribution"], "repository-only")

    def test_renderer_is_deterministic_and_credential_free(self) -> None:
        spec = importlib.util.spec_from_file_location("render_cli_reference", ROOT / "tools/render_cli_reference.py")
        assert spec and spec.loader
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        with mock.patch.dict(os.environ, {"COLUMNS": "120", "IMA_OPENAPI_APIKEY": "sentinel-secret"}), mock.patch.object(socket, "create_connection", side_effect=AssertionError("network access")), mock.patch.object(socket, "socket", side_effect=AssertionError("network access")):
            first = module.render()
        with mock.patch.dict(os.environ, {"COLUMNS": "40"}):
            self.assertEqual(first, module.render())
        self.assertIn("Generated by tools/render_cli_reference.py", first)
        self.assertNotIn("sentinel-secret", first)

    def test_help_surfaces_are_agent_friendly(self) -> None:
        spec = importlib.util.spec_from_file_location("render_cli_reference", ROOT / "tools/render_cli_reference.py")
        assert spec and spec.loader
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        parser = module.stable_parser()
        leaves = []
        arguments = []
        help_by_command = {}
        for path, current in module.walk_parsers(parser):
            command = "ima" + (" " + " ".join(path) if path else "")
            help_by_command[command] = " ".join(current.format_help().split())
            has_children = any(isinstance(action, argparse._SubParsersAction) for action in current._actions)
            self.assertTrue(current.description, command)
            self.assertTrue(current.epilog, command)
            if path and not has_children:
                leaves.append(command)
                self.assertIn("Example:", current.epilog, command)
                for action in current._actions:
                    if action.dest != "help":
                        arguments.append((command, action.dest))
                        self.assertIsInstance(action.help, str, f"{command}: {action.dest}")
                        self.assertTrue(action.help.strip(), f"{command}: {action.dest}")
                        self.assertNotEqual(action.help, argparse.SUPPRESS, f"{command}: {action.dest}")
        self.assertEqual(len(leaves), 22)
        self.assertEqual(len(arguments), 127)
        contracts = {
            "ima": ("IMA_OPENAPI_APIKEY", "exit 9", "exit 75"),
            "ima note create": ("Remote write", "UTF-8", "knowledge-base upload"),
            "ima kb search": ("not globally reranked", "exactly one --kb-id", "exits 9"),
            "ima kb add-url": ("1-10", "Retry only failed items"),
            "ima kb add-file": ("1-2000", "video is unsupported"),
            "ima kb read": ("4 MiB", "kb export"),
            "ima kb export": ("not overwritten", "--force"),
            "ima resolve": ("exact name", "id:", "alias:", "name:"),
            "ima alias set": ("configured account", "kb.research", "--force"),
        }
        for command, phrases in contracts.items():
            for phrase in phrases:
                self.assertIn(phrase.lower(), help_by_command[command].lower(), f"{command}: {phrase}")

    def test_checker_rejects_manifest_hash_link_and_frontmatter_drift(self) -> None:
        mutations = {
            "manifest": lambda root: (root / "skills/manifest.json").write_text((root / "skills/manifest.json").read_text(encoding="utf-8").replace('"tested_cli_version": "0.1.0"', '"tested_cli_version": "9.9.9"'), encoding="utf-8"),
            "hash": lambda root: (root / "third_party/ima-skills/1.1.9/original/meta.json").write_text("{}\n", encoding="utf-8"),
            "link": lambda root: (root / "README.md").write_text((root / "README.md").read_text(encoding="utf-8") + "\n[broken](missing-stage6-file.md)\n", encoding="utf-8"),
            "image_link": lambda root: (root / "README.md").write_text((root / "README.md").read_text(encoding="utf-8") + "\n![broken](missing-stage6-image.png)\n", encoding="utf-8"),
            "reference_link": lambda root: (root / "README.md").write_text((root / "README.md").read_text(encoding="utf-8") + "\n[broken-ref]: missing-stage6-ref.md\n", encoding="utf-8"),
            "frontmatter": self._empty_skill_description,
            "archive_hash": lambda root: (root / "third_party/ima-skills/1.1.9/UPSTREAM.json").write_text((root / "third_party/ima-skills/1.1.9/UPSTREAM.json").read_text(encoding="utf-8").replace('"archive_sha256": "8ee88bf653d905e91cee7ad95e44589f2de78db9c601d450807a144c09e89e33"', '"archive_sha256": "invalid"'), encoding="utf-8"),
            "attributes": lambda root: (root / ".gitattributes").write_text("", encoding="utf-8"),
            "recorded_at": lambda root: (root / "third_party/ima-skills/1.1.9/UPSTREAM.json").write_text((root / "third_party/ima-skills/1.1.9/UPSTREAM.json").read_text(encoding="utf-8").replace('"recorded_at": "2026-08-24"', '"recorded_at": "not-a-date"'), encoding="utf-8"),
        }
        for name, mutate in mutations.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory() as temp:
                root = Path(temp)
                self._copy_repository(root)
                mutate(root)
                result = self._run_checker(root)
                self.assertNotEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_new_parser_leaf_requires_skill_and_readme_coverage(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            self._copy_repository(root)
            parser_source = root / "src/ima_note_cli/knowledge_cli.py"
            text = parser_source.read_text(encoding="utf-8")
            marker = '    export = _command(\n'
            self.assertIn(marker, text)
            text = text.replace(marker, '    subparsers.add_parser("future-command", help="Mutation command.")\n' + marker)
            parser_source.write_text(text, encoding="utf-8")
            render = subprocess.run([sys.executable, str(root / "tools/render_cli_reference.py")], cwd=root, text=True, capture_output=True, check=False)
            self.assertEqual(render.returncode, 0, render.stdout + render.stderr)
            result = self._run_checker(root)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("future-command", result.stderr)

    def test_checker_rejects_archive_symlink(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            self._copy_repository(root)
            link = root / "third_party/ima-skills/1.1.9/original/escape-link"
            try:
                link.symlink_to(root / "README.md")
            except OSError as exc:
                self.skipTest(f"symlink creation unavailable: {exc}")
            result = self._run_checker(root)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("symlink/junction/reparse point", result.stderr)

    def test_uppercase_external_scheme_is_valid(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            self._copy_repository(root)
            readme = root / "README.md"
            readme.write_text(readme.read_text(encoding="utf-8") + "\n[uppercase](HTTPS://example.com/path)\n", encoding="utf-8")
            result = self._run_checker(root)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


if __name__ == "__main__":
    unittest.main()
